### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by githubGoblin** [Code-Pop/Vue-2-to-Vue-3#4]
```val.split('').reverse().join('') ``` was my first bet but it doesnt work. Since I had a little time to study, I looked at the code here and you have same mistake as me :)

```js
if (props.nameModifiers.reverse) {
        val = val.split('').reverse().join('')
}
```

**Comment by marina-mosti** [comment]
Hi @githubGoblin could you elaborate? What isnt working?

**Comment by githubGoblin** [comment]
Ok .. let's say I want to write '1' then '2' etc. so I have "123456".
"654321" in reverse. But actual string will be "642135".

**Comment by marina-mosti** [comment]
@githubGoblin you're right :) This seems like an unfortunate consequence of listening to the `input` event instead of the `change` event - as the `v-model` itself scrambles while the user types. 

Seems like the homework was a bit more complex than I anticipated 😅 

A really cool solution you could implement is that if the modifier is set, you listen to the change event instead!
